language: generic 
sudo: required

#指定docker为dependency:
services:
    - docker

#build React的image
before_install:
    - docker build -t fourt/react-test -f ./client/Dockerfile.dev ./client

#然后运行基于这个image的Container, 以便进行npm test.
scripts:
    - docker run -e CI=true fourt/react-test npm test

#build所有子项目的prod级别的images
after_success:
    - docker build -t fourt/multi-client ./client
    - docker build -t fourt/multi-nginx ./nginx
    - docker build -t fourt/multi-server ./server
    - docker build -t fourt/multi-worker ./worker

#将上述images push到Docker hub: 
    #需要先login Docker-hub: 在Travis里->设置->增加docker hub的变量,即用户名密码
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #将images推送到Docker hub
    - docker push fourt/multi-client
    - docker push fourt/multi-nginx
    - docker push fourt/multi-server
    - docker push fourt/multi-worker
    

